name: Feature Branch Build

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: build-site
        name: Build Site with Code Quality
        uses: ikmdev/yarn-code-quality-build-action@1.0.0
