name: Main Branch Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: build-site
        name: Build Site with Code Quality
        uses: ikmdev/yarn-code-quality-build-action@1.0.0
      - id: deploy-site
        name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          personal_token: ${{secrets.IKMDEVOPS_PAT_TOKEN}}
          publish_dir: ./build
          cname: www.ikm.dev
